create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  category text not null default 'Other',
  image text not null default '',
  demo_url text not null default '',
  github_url text not null default '',
  technologies text[] not null default '{}',
  status text not null default 'Live',
  featured boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.projects enable row level security;

create policy "public can read projects"
on public.projects for select
to anon, authenticated
using (true);

create policy "service role manages projects"
on public.projects for all
to service_role
using (true)
with check (true);
