-- Kylo database schema
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  category text not null default 'Other',
  image text not null default '',
  demo_url text not null default '',
  github_url text not null default '',
  technologies text[] not null default '{}',
  status text not null default 'Live',
  featured boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.projects enable row level security;
do $
begin
  create policy "public can read projects" on public.projects for select to anon, authenticated using (true);
exception when duplicate_object then null;
end $;
do $
begin
  create policy "service role manages projects" on public.projects for all to service_role using (true) with check (true);
exception when duplicate_object then null;
end $;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  client_name text not null,
  contact text not null,
  roblox_username text not null default '',
  project_type text not null,
  title text not null,
  description text not null default '',
  features text[] not null default '{}',
  links text[] not null default '{}',
  ai_complexity integer not null default 0 check (ai_complexity between 0 and 100),
  ai_min_robux integer not null default 0,
  ai_max_robux integer not null default 0,
  ai_timeline text not null default '',
  ai_reason text not null default '',
  final_robux integer,
  status text not null default 'REQUESTED',
  payment_status text not null default 'PENDING',
  client_token_hash text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  sender text not null check (sender in ('client','admin')),
  content text not null,
  created_at timestamptz not null default now()
);
create index if not exists orders_status_idx on public.orders(status);
create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists messages_order_id_idx on public.messages(order_id, created_at);
alter table public.orders enable row level security;
alter table public.messages enable row level security;
-- No public policies on orders/messages: Railway talks to Supabase with the server-side secret key.


create table if not exists public.order_events (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  event_type text not null,
  actor text not null default 'system' check (actor in ('client','admin','system')),
  details text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists order_events_order_id_idx on public.order_events(order_id, created_at);
alter table public.order_events enable row level security;
